Py2 to Py3 transition, use html_escape instead of cgi.escape, AttributeError: module 'cgi' has no attribute 'escape'
Signed-off-by: Wei Gao <wei.gao@windriver.com>